Update categorization decoration for workarea v3.5
workarea-commerce/workarea-browse-option pull request #3
Opened 2019-10-09 17:16 UTC by mttdffy

BROWSEOPTION-2

### FYIs 

This needs [workarea-commerce/workarea#156](https://github.com/workarea-commerce/workarea/pull/156) to be merged before working. 

@meowsus that this is going to require a minor. Added fix version on ticket, and am going to create a `v2.1-stable` for patches.

2019-10-10 13:30 UTC, bencrouse requested changes
Some test failures in the build.

2019-10-10 21:46 UTC, mttdffy commented
> Some test failures in the build.

> This needs workarea-commerce/workarea#156 to be merged before working.

2019-10-11 13:36 UTC, bencrouse commented
My bad, I merged https://github.com/workarea-commerce/workarea/pull/156, I'm rerunning checks now...

2019-10-11 14:30 UTC, bencrouse approved these changes

2019-10-11 14:30 UTC, merged