Update cache_key.decorator
workarea-commerce/workarea-browse-option pull request #5
Opened 2019-10-16 22:30 UTC by mcfearsome

Base on what I'm reading here: https://github.com/workarea-commerce/workarea-browse-option/blob/master/app/models/workarea/search/storefront/product_option.rb

and some experimentation in a shell:
```
irb(main):021:0> p.options['option']
=> "Dusty Blue"
irb(main):022:0> p.browse
p.browse_link_options   p.browse_option         p.browse_options        p.browse_swatch_option  p.browser_title
irb(main):022:0> p.browse_option
=> "color"
irb(main):023:0> p.options[p.browse_option]
=> nil
```

This looks like it needs to be updated

2019-10-17 13:14 UTC, tubbo requested changes

2019-10-17 13:14 UTC, tubbo commented on app/view_models/workarea/storefront/product_view_model/cache_key.decorator
> +      return super unless option.present? && @options['option'].present?
this won't work when the ProductViewModel is used in search results. we probably need both the original code and your new modifications, unfortunately...

2019-10-17 14:25 UTC, bencrouse requested changes
Looks like some relevant failing unit tests. What was the original bug report? We can take a deeper look if you don't want to sink more time into it @mcfearsome

2019-10-17 14:37 UTC, mcfearsome commented
@bencrouse https://jira.tools.weblinc.com/servicedesk/customer/portal/16/WAS-1963 was reported.  I took a peek and after a little digging saw that all browse_by_option products had the same cache key

2019-10-18 13:13 UTC, bencrouse reviewed
Thanks for jumping in @tubbo , the code looks good. Can you confirm the test failures are unrelated? Seems like they might be v3.5 related?

2019-10-18 17:25 UTC, tubbo approved these changes

2019-10-21 13:12 UTC, bencrouse approved these changes

2019-10-21 13:12 UTC, merged